In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
abdul = pd.read_csv("abdulbaqqi_skills.csv")
aishat = pd.read_csv("Aishat_Skill.csv")
bisola = pd.read_csv("Bisola_skills.csv")
feranmi = pd.read_csv("Oluwaferanmi_Skills.csv")
samuel = pd.read_csv("Samuel_Skill.csv").T
state = pd.read_csv("Statesman_skills.csv")
theo = pd.read_csv("TheophilusSkills.csv").T

In [3]:
abdul = pd.DataFrame(abdul).T
abdul_ = abdul.rename({"Skills":"Skills1"})
abdul1 = abdul_.drop("Unnamed: 0")
abdul1

0                  1                2             3
Skills1  python IOT  graphics designer  video animation  video editor

In [5]:
abu = abdul1[0].all().split(' ')
abdul1[0] = abu[0]
abdul1

0                  1                2             3
Skills1  python  graphics designer  video animation  video editor

In [6]:
aishat = pd.DataFrame(aishat)
aishat_ = aishat.drop('Unnamed: 0', axis='columns')
aishat_

Skill 1.  \
0  Excellent in Microsoft Office   

                                            Skill 2.  
0  Basic Knowledge of java, c programming and python

In [7]:
aishat_1 = str(aishat_['Skill 1.'].all()).split(' ')
aishat_11 = str(aishat_['Skill 2.'].all()).split(' ')
del aishat_1[0]
del aishat_1[0]
del aishat_11[0]
del aishat_11[0]
del aishat_11[0]
del aishat_11[3]
aishat_11[0] = aishat_11[0].strip(',')
aish = ' '.join(aishat_1)
aishat_11

['java', 'c', 'programming', 'python']

In [8]:
aishat12 = []
for i in aishat_11:
    aishat12.append(i)
aishat12.append(aish)
aishat12

['java', 'c', 'programming', 'python', 'Microsoft Office']

In [9]:
aishat_ = {'Skills2':aishat12}
aishat22 = pd.DataFrame(aishat_).T
aishat22

0  1            2       3                 4
Skills2  java  c  programming  python  Microsoft Office

In [10]:
bisola = pd.DataFrame(bisola).T
bisola3 = bisola.rename({'skills':"Skills3"})
bisola33 = bisola3.drop("Unnamed: 0")
bisola33

0        1       2         3         4        5         6
Skills3  Playing  Reading  Coding  Sleeping  Drinking  Smoking  Partying

In [11]:
feranmi_ = pd.DataFrame(feranmi).T
feranmi4 = feranmi_.rename({'Skills':"Skills4"})
feranmi4

0   1     2   3     4
Skills4  I  am  just  so  cool

In [12]:
samuel_ = pd.DataFrame(samuel).T
samuel5 = samuel_.rename({0:"Skills5"})
samuel5_ = samuel5.rename({'0':0, '1':1, '2':2, '3':3, '4':4}, axis='columns')
samuel55 = samuel5_.drop("Unnamed: 0", axis="columns")
samuel55

0                 1       2               3                4
Skills5  Python  Machine learning  MATLAB  Microsoft Word  Microsoft Excel

In [13]:
state_ = pd.DataFrame(state).T
state6 = state_.drop(["Unnamed: 0", "Ref"]).rename({"Skills":"Skills6"})
state6

0
Skills6  ['Basic level of python']

In [14]:
Skills_6 = list(state6[0].all().split(' '))
state6_ = Skills_6[3].strip("']")
state = [state6_]
state_6 = pd.DataFrame(state).T
state66 = state_6.rename({0:"Skills6"})
state66

0
Skills6  python

In [15]:
theo_ = pd.DataFrame(theo).T
theo7 = theo_.drop('Unnamed: 0', axis='columns')
theo7_7 = theo7.rename({0:"Skills7"})
theo77 = theo7_7.rename({'0':0, '1':1, '2':2, '3':3, '4':4}, axis='columns')
theo77

0        1          2          3       4
Skills7  Python,  Machine  learning,  microsoft  office

In [16]:
theo77[0] = theo77[0].all().strip(',')
theo77

0        1          2          3       4
Skills7  Python  Machine  learning,  microsoft  office

In [17]:
cat = pd.concat([abdul1, aishat22, bisola33, feranmi4, samuel55, state66, theo77], sort=True)
cat

0                  1                2               3  \
Skills1   python  graphics designer  video animation    video editor   
Skills2     java                  c      programming          python   
Skills3  Playing            Reading           Coding        Sleeping   
Skills4        I                 am             just              so   
Skills5   Python   Machine learning           MATLAB  Microsoft Word   
Skills6   python                NaN              NaN             NaN   
Skills7   Python            Machine        learning,       microsoft   

                        4        5         6  
Skills1               NaN      NaN       NaN  
Skills2  Microsoft Office      NaN       NaN  
Skills3          Drinking  Smoking  Partying  
Skills4              cool      NaN       NaN  
Skills5   Microsoft Excel      NaN       NaN  
Skills6               NaN      NaN       NaN  
Skills7            office      NaN       NaN

In [18]:
cat[0]

Skills1     python
Skills2       java
Skills3    Playing
Skills4          I
Skills5     Python
Skills6     python
Skills7     Python
Name: 0, dtype: object

In [19]:
n1 = cat[0].unique()
n1

array(['python', 'java', 'Playing', 'I', 'Python'], dtype=object)

In [33]:
n2 = cat[1].unique()
n2

array(['graphics designer', 'c', 'Reading', 'am', 'Machine learning', nan,
       'Machine'], dtype=object)

In [21]:
n3 = cat[2].unique()
n3

array(['video animation', 'programming', 'Coding', 'just', 'MATLAB', nan,
       'learning,'], dtype=object)

In [22]:
n4 = cat[3].unique()
n4

array(['video editor', 'python', 'Sleeping', 'so', 'Microsoft Word', nan,
       'microsoft'], dtype=object)

In [23]:
n5 = cat[4].unique()
n5

array([nan, 'Microsoft Office', 'Drinking', 'cool', 'Microsoft Excel',
       'office'], dtype=object)

In [24]:
n6 = cat[5].unique()
n6

array([nan, 'Smoking'], dtype=object)

In [25]:
n7 = cat[6].unique()
n7

array([nan, 'Partying'], dtype=object)

In [39]:
n = []
for i in n1:
    n.append(i)
for i in n2:
    n.append(i)
for i in n3:
    n.append(i)
for i in n4:
    n.append(i)
for i in n5:
    n.append(i)
for i in n6:
    n.append(i)
for i in n7:
    n.append(i)
n

['python',
 'java',
 'Playing',
 'I',
 'Python',
 'graphics designer',
 'c',
 'Reading',
 'am',
 'Machine learning',
 nan,
 'Machine',
 'video animation',
 'programming',
 'Coding',
 'just',
 'MATLAB',
 nan,
 'learning,',
 'video editor',
 'python',
 'Sleeping',
 'so',
 'Microsoft Word',
 nan,
 'microsoft',
 nan,
 'Microsoft Office',
 'Drinking',
 'cool',
 'Microsoft Excel',
 'office',
 nan,
 'Smoking',
 nan,
 'Partying']

In [46]:
for i in n:
    if i.type != dtypes(float):
        i = i.upper()
n

AttributeError: 'str' object has no attribute 'type'

In [ ]:
cat.stack().value_counts()